#---------------------------------#
#      general configuration      #
#---------------------------------#

version: {build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

clone_depth: 1

install:
  - cmd: dotnet restore

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

#---------------------------------#
#         notifications           #
#---------------------------------#
